apps/home/forms.py
# -*- encoding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import TextAreaField, PasswordField , SubmitField, SelectField
from wtforms.validators import InputRequired, Email, DataRequired

## Settings


class UpdateSettingsForm(FlaskForm):
    firstname = TextAreaField('firstname'     , id='firstname_create')
    lastname = TextAreaField('lastname'     , id='last_create')
    phonenumber = TextAreaField('phonenumber'     , id='phonenumber_create')
    dob = TextAreaField('dob'     , id='dob')
    gender = SelectField('gender'     , id='gender', choices=[('', 'Select Gender'), ('female', 'Female'), ('male', 'Male')])
    city = TextAreaField('city'     , id='city')
    zip = TextAreaField('zip'     , id='zip')
    address = TextAreaField('address'     , id='address')
    houseno = TextAreaField('houseno', id='houseno')
    saveall = SubmitField('saveall')


class DashboardForm(FlaskForm):
    source = TextAreaField('source', id='source')
    destination = TextAreaField('destination', id='destination')
    cartype = SelectField('cartype', id='cartype', choices=[('', 'View car types'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Limousine', 'Limousine')])
    book = SubmitField('book')

"""class ReloadAmountForm(FlaskForm):    
    amount"""

apps/home/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-

from apps.home import blueprint
from flask import render_template, redirect, url_for, request, session, send_file, flash, Response
from flask_login import login_required, current_user

from jinja2 import TemplateNotFound
from apps.home.forms import UpdateSettingsForm, DashboardForm
from apps.authentication.models import User, Car, Ride
from apps import db, login_manager
import boto3
from datetime import date,datetime
import random
import requests, json
import re
from werkzeug.utils import secure_filename
from apps.credentials import access_key, secret_access_key, google_api_key
from sqlalchemy import func


s3 = boto3.client('s3',
                  aws_access_key_id=access_key,
                  aws_secret_access_key=secret_access_key)

BUCKET_NAME = "s3-bucket-281"

@blueprint.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    dashboard_form = DashboardForm(request.form)
    if 'book' in request.form:
        cartype = request.form['cartype']
        car = Car.query.filter_by(cartype=cartype, active='false').first()
        user = User.query.filter_by(username=current_user.username).first()
        today = date.today()
        if (car != None):
            car.active = 'true'
            user_id = user.id
            distance, duration, fare, rewards = calculateDistance(request.form['source'], request.form['destination'], cartype)
            print("rewards", rewards)
            ride = Ride(
                ride=car,
                source=request.form['source'],
                destination=request.form['destination'],
                userId=user_id,
                ride_date=today,
                trip_status="Booked",
                payment=0,
                est_amount=fare,
                rewards= rewards
            )
            db.session.add(ride)
            db.session.commit()
            return render_template('home/dashboard.html', segment='dashboard', form=dashboard_form, car=car, est_amt=fare,
                                   est_dur=duration,rewards=rewards)
        else:
            car_type = request.form['cartype']
            return render_template('home/dashboard.html', segment='dashboard', form=dashboard_form, error=True,
                                   carType=car_type)
    elif 'schedule' in request.form:
        cartype = request.form['cartype']
        car = Car.query.filter_by(cartype=cartype, active='false').first()
        user = User.query.filter_by(username=current_user.username).first()
        ride_sch = request.form['appt']
        ride_sch_obj = datetime.strptime(ride_sch,
                                 "%Y-%m-%dT%H:%M")
        print(ride_sch_obj)
        ride_day = ride_sch_obj.date()
        if (car != None):
            car.active = 'false'
            user_id = user.id
            distance, duration, fare, rewards = calculateDistance(request.form['source'], request.form['destination'], cartype)
            print("fare", fare)
            print("duration", duration)
            ride = Ride(
                ride=car,
                source=request.form['source'],
                destination=request.form['destination'],
                userId=user_id,
                ride_date=ride_day,
                trip_status="Scheduled",
                payment=0,
                est_amount=fare,
                rewards=rewards
            )
            db.session.add(ride)
            db.session.commit()
            return render_template('home/dashboard.html', segment='dashboard', form=dashboard_form, car=car, est_amt=fare,
                                   est_dur=duration, scheduled_ride= ride_sch_obj, rewards=rewards)
    else:
        return render_template('home/dashboard.html', segment='dashboard', form=dashboard_form)


def calculateDistance(source, dest, cartype):
    # Setting base price
    base_price = 2

    # enter your api key here
    api_key = google_api_key

    # url variable store url
    url = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=" + source + "&destinations=" + dest + "&key=" + api_key

    # return response object
    r = requests.get(url)

    # return json format result
    x = r.json()

    distance = x['rows'][0]['elements'][0]['distance']['text']
    duration = x['rows'][0]['elements'][0]['duration']['text']

    distance = re.findall('\d*\.?\d+', distance)[0]

    # Converting distance in km to miles
    distance = round(float(distance) * 0.62, 2)

    # Calculating price based on base price
    fare = round(distance * base_price, 2)


# Fares: sedan= fare *1 , SUV =fare*1.5 ,Limousine =fare*2
    if cartype == "SUV":
        fare = round(fare*1.5)
    elif cartype == "Limousine":
        fare *= 2

    rewards = round((fare * 0.1), 2)
    print(rewards)
    return distance, duration, fare, rewards


@blueprint.route('/dashboard-admin', methods=['GET', 'POST'])
@login_required
def dashboardadmin():
    page = request.args.get('page', 1, type=int)
    page1 = request.args.get('page1', 1, type=int)

    # data = Car.query.paginate(page=page, per_page=5)  # data from database
    car_data = Car.query.order_by(Car.id.desc()).paginate(page=page, per_page=5)
    user_data = User.query.paginate(page=page1, per_page=5)

    random_no = []
    for row in car_data.items:
        random_no.append(random.randint(50, 100))

    move_state = []
    for row in car_data.items:
        move_state.append(random.choice(['stopped', 'forward', 'backward', 'idle']))

    return render_template('home/dashboard-admin.html', query=car_data, user_query=user_data,
                           battery=random_no, state=move_state, zip=zip)


@blueprint.route('/dashboard-owner', methods=['GET', 'POST'])
@login_required
def dashboardowner():
    data = Car.query.filter_by(user_id=current_user.id).all()  # data from database
    carrides_owned = []
    Amount = 0
    for i in data:
        rides = Ride.query.filter_by(car_id=i.id).all()
        carrides_owned.extend(rides)

    for i in carrides_owned:
        if i.trip_status == "Completed":
            i.payment = i.est_amount
            print(i.payment)
        Amount = int(int(Amount) + int(i.payment))
    db.session.commit()
    return render_template('home/dashboard-owner.html', query=data, carrides=carrides_owned, user=current_user,
                           amount=Amount)


@blueprint.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    setting_form = UpdateSettingsForm(request.form)
    print(current_user.firstname)
    if 'saveall' in request.form:
        user = User.query.filter_by(username=current_user.username).first()
        if user:
            user.firstname = request.form['firstname']
            user.lastname = request.form['lastname']
            user.address = request.form['address']
            user.city = request.form['city']
            user.zip = request.form['zip']
            user.houseno = request.form['houseno']
            user.dob = request.form['dob']
            user.gender = request.form['gender']
            user.phonenumber = request.form['phonenumber']
            db.session.commit()

    return render_template('home/settings.html', form=setting_form)


@blueprint.route('/stats', methods=['GET'])
@login_required
def stats():
    # data from database
    total_users = User.query.filter(User.id).count()
    total_cars = Car.query.filter(Car.id).count()
    system_admin = User.query.filter_by(role='admin').count()
    car_owners = User.query.filter_by(role= 'owner').count()
    car_users = User.query.filter_by(role='user').count()
    num_cars = Car.query.filter(Car.user_id).count()
    num_suv = Car.query.filter_by(cartype='SUV').count()
    num_limo = Car.query.filter_by(cartype='Limousine').count()
    active_cars = Car.query.filter_by(active='true').count()
    inactive_cars = num_cars - active_cars

    num_tesla = Car.query.filter(Car.carmodel.like('Tesla %')).count()
    num_lucid = Car.query.filter(Car.carmodel.like('Lucid %')).count()
    num_hyundai = Car.query.filter(Car.carmodel.like('Hyundai %')).count()
    num_honda = Car.query.filter(Car.carmodel.like('Honda %')).count()

    num_sedan = Car.query.filter_by(cartype='Sedan').count()
    car_models = Car.query.filter_by(carmodel=Car.carmodel).all()
    all_carmodels = []
    for car in car_models:
        all_carmodels.append(car.carmodel)
    return render_template('home/stats.html',
                           total_users=total_users,
                           total_cars=total_cars,
                           system_admin=system_admin,
                           car_owners=car_owners,
                           car_users=car_users,
                           num_sedan=num_sedan,
                           num_suv=num_suv,
                           num_limo=num_limo,
                           active_cars=active_cars,
                           inactive_cars=inactive_cars,
                           num_tesla=num_tesla,
                           num_lucid=num_lucid,
                           num_hyundai=num_hyundai,
                           num_honda=num_honda,
                           all_carmodels=all_carmodels
                           )


@blueprint.route('/transactions', methods=['GET', 'POST'])
@login_required
def transactions():
    page = request.args.get('page2', 1, type=int)
    data = Ride.query.filter_by(userId=current_user.id).paginate(page=page, per_page=5)  # data from database

    for val in data.items:
        if val.trip_status == "Completed":
            current_user.amount = current_user.amount - int(val.est_amount)
            val.payment = current_user.amount
            db.session.commit()

    if request.method == "POST":
        add_amount = request.form["add_amount"]
        current_user.amount = current_user.amount + int(add_amount)
        db.session.commit()

    return render_template('home/transactions.html', tripRecord=data, count=len(data.items),

apps/templates/home/dashboard-admin.html
{% extends "layouts/base.html" %}

{% block title %} Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div>
    <span><a href="{{ url_for('home_blueprint.dashboardsensordata') }}" class="btn btn-primary"
        type="button">Access Sensor Data</a></span>
    <span><a href="{{ url_for('home_blueprint.dashboardimagedb') }}" class="btn btn-primary"
        type="button">Access Image Data</a></span>
</div>
<div class="card border-light shadow-sm mb-4 mt-4">
    <div class="card-header d-sm-flex flex-row align-items-center flex-0">
        <div class="d-block mb-3 mb-sm-0">
            <div class="h5 fw-normal mb-2">All Vehicle Information</div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                        <th class="border-0">Vehicle Model</th>
                        <th class="border-0">Vehicle Number</th>
                        <th class="border-0">Vehicle Color</th>
                        <th class="border-0">Vehicle Type</th>
                        <th class="border-0">Service States</th>
                        <th class="border-0">Vehicle Battery</th>
                        <th class="border-0">Road Service</th>
                        <th class="border-0">Moving State</th>
                        <th class="border-0">Vehicle Miles</th>

                    </tr>
                </thead>
                <tbody>
                    <!-- Item -->

                    {% for row, num in zip(query.items, battery) %}
                    <tr>
                        <td class="border-0 fw-bold">
                            {{row.carmodel}}
                        </td>
                        <td class="border-0">
                            {{row.carNo}}
                        </td>
                        <td class="border-0">
                            {{row.carcolor}}
                        </td>
                        <td class="border-0">
                            {{row.cartype}}
                        </td>
                        <td class="border-0">
                            {% if row.active == 'true'%}
                            Active
                            {% else %}
                            Inactive
                            {%endif%}
                        </td>
                        <td class="border-0">
                            <div class="row d-flex align-items-center">
                                <div class="col-12 col-xl-2 px-0">
                                    <div class="small fw-bold">{{num}}%</div>
                                </div>
                                <div class="col-12 col-xl-10 px-0 px-xl-1">
                                    <div class="progress progress-lg mb-0">
                                        <div class="progress-bar bg-dark" role="progressbar" aria-valuenow="{{num}}"
                                            aria-valuemin="0" aria-valuemax="100" style="width: {{num}}%;"></div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    <td class="border-0">
                        {{ row.roadService }}
                    </td>
                    <td class="border-0">
                        {%  if row.active == 'true' %}
                        Moving
                        {% else %}
                        Idle
                        {%  endif %}
                    </td>
                    <td class="border-0">
                            <div class="small fw-bold">{{row.miles}}</div>
                    </td>
                    </tr>
                    {% endfor %}
                    <!-- End of Item -->
                </tbody>
            </table>
            <div class="card-footer" style="padding-bottom: 0px;">
                <!-- Pagination Links-->
                <div class="text-right">
                    <a href="{{ url_for('home_blueprint.dashboardadmin', page=query.prev_num) }}" class="btn btn-outline-dark
                    {% if query.page == 1 %}disabled{% endif %}" style="padding: 0.35rem 0.65rem; font-size: 0.8rem;">
                        &laquo;
                    </a>
                    <!-- Loop through the number of pages to display a link for each-->
                    {% for page_num in query.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)
                    %}
                    {% if page_num %}
                    <!-- Check for the active page and set the link to "Active"-->
                    {% if query.page == page_num %}
                    <a href="{{ url_for('home_blueprint.dashboardadmin', page=page_num) }}" class="btn btn-dark"
                        style="padding: 0.35rem 0.65rem; font-size: 0.8rem;">
                        {{ page_num }}
                    </a>
                    {% else %}
                    <a href="{{ url_for('home_blueprint.dashboardadmin', page=page_num) }}" class="btn btn-outline-dark"
                        style="padding: 0.35rem 0.65rem; font-size: 0.8rem;">
                        {{ page_num }}
                    </a>
                    {% endif %}
                    {% else %}
                    ...
                    {% endif %}
                    {% endfor %}
                    <a href="{{ url_for('home_blueprint.dashboardadmin', page=query.next_num) }}" class="btn btn-outline-dark
       {% if query.page == query.pages %}disabled{% endif %}" style="padding: 0.35rem 0.65rem; font-size: 0.8rem;">
                        &raquo;
                    </a>
                </div>
                <p class="text-right mt-3" style="font-size: 12px;">
                    Showing page {{ query.page }} of {{ query.pages }}
                </p>
            </div>
        </div>
    </div>
</div>

<div class="card border-light shadow-sm">
    <div class="card-header d-sm-flex flex-row align-items-center flex-0">
        <div class="d-block mb-3 mb-sm-0">
            <div class="h5 fw-normal mb-2">All Registered Users</div>
        </div>
    </div>
{#    <div class="media d-flex align-items-center">#}
{#              <img id="avatar" alt="Image placeholder"#}
{#                src="/static/assets/img/team/profile-picture-2.jpg">#}
{#    </div>#}
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                        <th class="border-0">Username</th>
                        <th class="border-0">Role</th>
                        <th class="border-0">Email</th>
                        <th class="border-0">Phone Number</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Item -->
                    {% for row in user_query.items %}
                    <tr>
                        <td class="border-0">
                            {{row.username}}
                        </td>
                        <td class="border-0">
                            {{row.role}}
                        </td>
                        <td class="border-0">
                            {{row.email}}
                        </td>
                        <td class="border-0">
                            {{row.phonenumber}}
                        </td>
                    </tr>
                    {% endfor %}
                    <!-- End of Item -->
                </tbody>
            </table>
            <div class="card-footer" style="padding-bottom: 0px;">
                <!-- Pagination Links-->
                <div class="text-right">
                    <a href="{{ url_for('home_blueprint.dashboardadmin', page1=user_query.prev_num) }}" class="btn btn-outline-dark
                    {% if user_query.page == 1 %}disabled{% endif %}"
                        style="padding: 0.35rem 0.65rem; font-size: 0.8rem;">
                        &laquo;
                    </a>
                    <!-- Loop through the number of pages to display a link for each-->
                    {% for page_num in user_query.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)
                    %}
                    {% if page_num %}
                    <!-- Check for the active page and set the link to "Active"-->
                    {% if user_query.page == page_num %}
                    <a href="{{ url_for('home_blueprint.dashboardadmin', page1=page_num) }}" class="btn btn-dark"
                        style="padding: 0.35rem 0.65rem; font-size: 0.8rem;">
                        {{ page_num }}
                    </a>
                    {% else %}
                    <a href="{{ url_for('home_blueprint.dashboardadmin', page1=page_num) }}"
                        class="btn btn-outline-dark" style="padding: 0.35rem 0.65rem; font-size: 0.8rem;">
                        {{ page_num }}
                    </a>
                    {% endif %}
                    {% else %}
                    ...
                    {% endif %}
                    {% endfor %}
                    <a href="{{ url_for('home_blueprint.dashboardadmin', page1=user_query.next_num) }}" class="btn btn-outline-dark
       {% if user_query.page == user_query.pages %}disabled{% endif %}"
                        style="padding: 0.35rem 0.65rem; font-size: 0.8rem;">
                        &raquo;
                    </a>
                </div>
                <p class="text-right mt-3" style="font-size: 12px;">
                    Showing page {{ user_query.page }} of {{ user_query.pages }}
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/dashboard-imagedb.html
{% extends "layouts/base.html" %}

{% block title %} Image Data   {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="card border-light shadow-sm mb-4 mt-4">
    <div class="card-header d-sm-flex flex-row align-items-center flex-0">
        <div class="d-block mb-3 mb-sm-0">
            <div class="h5 fw-normal mb-2">All Car Images</div>
            <!-- <p>Created: {{ files.creation_date }}</p> -->
            <!-- <p>{{files }}</p> -->
        </div>
    </div>
    <table class="table table-striped">
        <tr>
          <th>Filename</th>
          <!-- <th>Last Modified</th> -->
          <th>Action</th>
        </tr>
        {% for f in files %}
        <tr>
          <td>{{ f }}</td>
          <!-- <td>{{ f.last_modified }}</td> -->
          <td class="td-buttons d-flex">
            <!-- <form class="delete-form" action="{{ url_for('home_blueprint.delete') }}" method="POST">
              <input type="hidden" name="key" value="{{ f }}">
              <button type="submit" class="btn btn-danger btn-sm">
                <i class="fa fa-trash-alt"></i>
              </button>
            </form> -->
            <form class="download-form" action="{{ url_for('home_blueprint.download') }}" method="POST">
              <input type="hidden" name="key" value="{{ f }}">
              <button type="submit" class="btn btn-default btn-sm">
                <i class="fa fa-download"></i>
              </button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </table>
</div>
<!-- <div class="content">
  <div>
    <h3>Here are media files inside the S3 bucket:</h3>
    <ul>
      {% for item in contents %}
        <li>
          <img src={{ item }} style="width: 250px">
        </li>
      {% endfor %}
    </ul>
  </div>
</div> -->


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/dashboard-owner.html
{% extends "layouts/base.html" %}

{% block title %} Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div style="text-align: center; margin: auto; width: 37%;">
    <div class="card border-light shadow-sm" style="background-image: linear-gradient(350deg, #18151a, #0221ac);
     padding: 4%;">
        <div class="card-body">
            <div class="row d-block d-xl-flex align-items-center">
                <div class="d-none d-sm-block mb-4">
                    <h2 class="h5" style="color: white;">{{user.username}}</h2>
                    <h3 class="mb-1" style="color: white;">Available Amount: $ {{'%0.2f' % amount|float}}
                    </h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card border-light shadow-sm mb-4 mt-4">
    <div class="card-header d-sm-flex flex-row align-items-center flex-0">
        <div class="d-block mb-3 mb-sm-0">
            <div class="h5 fw-normal mb-2">Car Information</div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                    <tr>

                        <th class="border-0">Car Model</th>
                        <th class="border-0">Car No</th>
                        <th class="border-0">Car Color</th>
                        <th class="border-0">Car Type</th>
                        <th class="border-0">Car Status</th>
                        <th class="border-0">Battery</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Item -->

                    {% for row in query %}
                    <tr>
                        <td class="border-0 fw-bold">
                            {{row.carmodel}}
                        </td>
                        <td class="border-0">
                            {{row.carNo}}
                        </td>
                        <td class="border-0">
                            {{row.carcolor}}
                        </td>
                        <td class="border-0">
                            {{row.cartype}}
                        </td>
                        <td class="border-0">
                            {% if row.active == 'true'%}
                            Active
                            {% else %}
                            Inactive
                            {%endif%}
                        </td>
                        <td class="border-0">
                            <div class="row d-flex align-items-center">
                                <div class="col-12 col-xl-2 px-0">
                                    <div class="small fw-bold">51%</div>
                                </div>
                                <div class="col-12 col-xl-10 px-0 px-xl-1">
                                    <div class="progress progress-lg mb-0">
                                        <div class="progress-bar bg-dark" role="progressbar" aria-valuenow="51"
                                            aria-valuemin="0" aria-valuemax="100" style="width: 51%;"></div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    <!-- End of Item -->
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="card border-light shadow-sm">
    <div class="card-header d-sm-flex flex-row align-items-center flex-0">
        <div class="d-block mb-3 mb-sm-0">
            <div class="h5 fw-normal mb-2">Rides Taken</div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                        <th class="border-0">#</th>
                        <th class="border-0">Source</th>
                        <th class="border-0">Destination</th>
                        <th class="border-0">Date</th>
                        <th class="border-0">Trip Status</th>
                        <th class="border-0">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Item -->

                    {% for row in carrides %}
                    <tr>
                        <td class="border-0 fw-bold">
                            {{loop.index}}
                        </td>
                        <td class="border-0">
                            {{row.source}}
                        </td>
                        <td class="border-0">
                            {{row.destination}}
                        </td>
                        <td class="border-0">
                            {{row.ride_date}}
                        </td>
                        {% if row.trip_status == 'Complete' %}
                        <td class="border-0" style="color: #15cb15;">
                            {{row.trip_status}}
                        </td>
                        {% elif row.trip_status == 'Cancelled' %}
                        <td class="border-0" style="color: red;">
                            {{row.trip_status}}
                        </td>
                        {% else %}
                        <td class="border-0" style="color: #ffb300;">
                            {{row.trip_status}}
                        </td>
                        {% endif %}
                        <td class="border-0">
                            {{row.payment}}
                        </td>
                    </tr>
                    {% endfor %}
                    <!-- End of Item -->

                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="vh-100 d-flex align-items-center justify-content-center">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center d-flex align-items-center justify-content-center">
                        <div>
                            <img class="img-fluid w-75" src="/static/assets/img/illustrations/404.svg" alt="404 not found">
                            <h1 class="mt-5">Page not <span class="fw-bolder text-primary">found</span></h1>
                            <p class="lead my-4">Oops! Looks like you followed a bad link. If you think this is a problem with us, please tell us.</p>
                            <a href="/dashboard.html" class="btn btn-gray-800 d-inline-flex align-items-center justify-content-center mb-4">
                                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
                                Back to homepage
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}